CREATE DATABASE Grocery_Store_Management;
USE Grocery_Store_Management;
SHOW TABLES;

-- 1. Supplier Table
CREATE TABLE suppliers (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

-- 2. Categories Table
CREATE TABLE categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

-- 3. Employees Table
CREATE TABLE employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

-- 4. Customers Table
CREATE TABLE customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

-- 5. Products Table
CREATE TABLE products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES suppliers(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Orders Table
CREATE TABLE orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 7. Order_Details Table
CREATE TABLE order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

select * from categories;
select * from customers;
select * from employees;
select * from order_details;
select * from orders;
select * from products;
select * from suppliers;

-- Customer Insights

-- 1.How many unique customers have placed orders?

select count(distinct (cust_id)) as unique_cust 
from orders;

-- 2.Which customers have placed the highest number of orders?

select customers.cust_id,cust_name,count(orders.ord_id) as total_orders
from customers
join orders on orders.cust_id = customers.cust_id
group by customers.cust_name,customers.cust_id
order by total_orders desc
limit 5;

-- 3.What is the total and average purchase value per customer?

select c.cust_id,c.cust_name, sum(total_price) as total,avg(total_price) as avg_purchase
from order_details od
join orders o on o.ord_id = od.ord_id
join customers c on c.cust_id = o.cust_id
group by c.cust_name,c.cust_id
order by total desc;

-- 4.Who are the top 5 customers by total purchase amount?

select c.cust_id,c.cust_name, sum(total_price) as total
from order_details od
join orders o on o.ord_id = od.ord_id
join customers c on c.cust_id = o.cust_id
group by c.cust_name,c.cust_id
order by total desc
limit 5;

-- Product Performance

-- 1.How many products exist in each category?

select cat_name,count(prod_name) as product_count
from categories c
join products p on p.cat_id=c.cat_id
group by cat_name;

-- 2.What is the average price of products by category?

select c.cat_name,avg(p.price) as prod_avg_price
from categories c
join products p on c.cat_id = p.cat_id
group by cat_name;

-- 3.Which products have the highest total sales volume (by quantity)?

select p.prod_name,sum(od.quantity) as total_quantity
from products p
join order_details od on p.prod_id=od.prod_id
group by p.prod_name
order by total_quantity desc
limit 5;

-- 4.What is the total revenue generated by each product?

select p.prod_name,sum(od.total_price) as total_revenue
from products p
join order_details od on od.prod_id=p.prod_id
group  by p.prod_name;

-- 5.How do product sales vary by category and supplier?

select c.cat_name,s.sup_name,p.prod_name,
    sum(od.quantity * od.total_price) as total_sales
from order_details od
join products p on p.prod_id = od.prod_id
join categories c on c.cat_id = p.cat_id
join suppliers s on s.sup_id = p.sup_id
group by c.cat_name, s.sup_name, p.prod_name
order by total_sales desc;

-- Sales and Order Trends

-- 1.How many orders have been placed in total?

select count(distinct od.ord_id) as total_orders
from order_details od;

-- 2.What is the average value per order?

select avg(order_total) as avg_price_per_order
from (
  select od.ord_id, sum(od.total_price) as order_total
  from order_details od
  group by od.ord_id
) t;



-- 3.On which dates were the most orders placed?

select o.order_date,count(*) as orders_count
from orders o
group by o.order_date
order by orders_count desc
limit 5;


-- 4.How do order patterns vary across weekdays and weekends?

select 
  case when weekday(o.order_date) < 5 then 'weekday' else 'weekend' end as day_type,
  count(distinct o.ord_id) as orders_count,
  sum(od.quantity * od.each_price) as total_revenue
from orders o
join order_details od on od.ord_id = o.ord_id
group by day_type
order by orders_count desc;

-- Supplier Contribution

-- 1.How many suppliers are there in the database?

select count(sup_id) as total_suppliers 
from suppliers;

-- 2.Which supplier provides the most products?

select s.sup_name,s.sup_id,count(distinct p.prod_name) as Prod_count
from suppliers s
join products p on s.sup_id=p.sup_id
group by s.sup_id,s.sup_name
order by Prod_count desc
limit 5;

-- 3.What is the average price of products from each supplier?

select s.sup_id,s.sup_name,avg(p.price) as avg_price_prod_supplier
from suppliers s
join products p on s.sup_id=p.sup_id
group by s.sup_id,s.sup_name;

-- 4.Which suppliers contribute the most to total product sales (by revenue)?

select s.sup_id, s.sup_name, sum(od.total_price) as revenue
from suppliers s
join products p on s.sup_id = p.sup_id
join order_details od on p.prod_id = od.prod_id
group by s.sup_id, s.sup_name
order by revenue desc;

-- Employee Performance

-- 1.How many employees have processed orders?

select count(distinct emp_id) as employees_processed_orders
from orders
where emp_id is not null;

-- 2.Which employees have handled the most orders?

select e.emp_id, e.emp_name, count(o.ord_id) as orders_handled
from employees e
join orders o on e.emp_id = o.emp_id
group by e.emp_id, e.emp_name
order by orders_handled desc;

-- 3.What is the total sales value processed by each employee?

select e.emp_id,e.emp_name,sum(od.total_price) as total_sales_value
from employees e
join orders o on o.emp_id=e.emp_id
join order_details od on od.ord_id=o.ord_id
group by e.emp_id,e.emp_name;



-- 4.What is the average order value handled per employee

select e.emp_id, e.emp_name, avg(order_tot.order_total) as avg_order_value
from employees e
join orders o on e.emp_id = o.emp_id
left join (
    select ord_id, sum(total_price) as order_total
    from order_details
    group by ord_id
) order_tot on order_tot.ord_id = o.ord_id
group by e.emp_id, e.emp_name
order by avg_order_value desc;


-- Order Details Deep Dive

-- 1.What is the relationship between quantity ordered and total price?

select round(corr(od.quantity, od.total_price),3) as qty_totalprice_corr
from order_details od;

-- 2.What is the average quantity ordered per product?

select p.prod_id, p.prod_name, avg(od.quantity) as avg_qty
from products p
left join order_details od on p.prod_id = od.prod_id
group by p.prod_id, p.prod_name
order by avg_qty desc;

-- 3.How does the unit price vary across products and orders?

select prod_id, prod_name,
       min(each_price) as min_unit_price,
       max(each_price) as max_unit_price,
       avg(each_price) as avg_unit_price
from (
    select p.prod_id, p.prod_name, od.each_price
    from products p
    left join order_details od on p.prod_id = od.prod_id
) t
group by prod_id, prod_name
order by avg_unit_price desc;

